# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YSG' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YSG
pod 'jastor', '~> 0.2.1'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'WebViewJavascriptBridge', '~> 5.0'
    pod 'SDWebImage'
end
